version: '3.8'

services:
  splitpay-app:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - redis
    environment:
      DB_database: ${DB_database}
      DB_user: ${DB_user}
      DB_password: ${DB_password}
      DB_HOST: ${DB_HOST}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
    networks:
      - my-networks    
    
  
  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3301:3306"
    expose:
      - "3306"  
    volumes:
      - dbdata:/data/db  
    networks:
      - my-networks    
    environment:
      MYSQL_DATABASE: ${DB_database}
      MYSQL_PASSWORD: ${DB_password}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_user}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    networks:
      - my-networks  
    volumes:
      - ./redis-data:/data    
    restart: always  
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}  
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}


volumes:
  dbdata:
  redis-data:

networks:
  my-networks:
    driver: bridge  

