version: '3.8'

services:
  splitpay-app:
    image: emzm17/splitpay-app
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    env_file: .env
    environment:
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: '${DB_HOST}'
      SECRET_KEY: '${SECRET_KEY}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
    volumes:
      - my-data:/usr/src/app/data  # Named volume for shared data
    networks:
      - my-networks

networks:
  my-networks:
    driver: overlay  # Use overlay driver for Swarm mode

volumes:
  my-data:
    driver: local
